repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Pin to a specific, recent release of ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
