name: build-alpine-single-exe

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  workflow_dispatch:

env:
  APP_NAME: zte                   # output binary will be dist/bin/zte
  PY_VER: "3.12"                  # target Python version for embedding
  # using console_script entry point defined in pyproject.toml
  EXEC_ENTRYPOINT: cli.zte:cli    # matches [project.scripts].zte = "cli.zte:cli"

jobs:
  build:
    name: Alpine musl build (x86_64)
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Prepare Alpine toolchain
        run: |
          apk add --no-cache \
            bash curl git ca-certificates \
            build-base pkgconfig \
            rust cargo \
            openssl-dev zlib-dev xz zstd

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          # make uv available in this step and the next ones
          export PATH="${HOME}/.local/bin:${PATH}"
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          uv --version

      - name: Cache uv downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
          key: uv-${{ runner.os }}-${{ env.PY_VER }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ env.PY_VER }}-

      - name: Build wheel/sdist
        run: |
          # Build project distributions without creating a venv (fast)
          uv build --python ${PY_VER} --wheel --sdist
          ls -lah dist

      - name: Resolve wheel path
        id: wheel
        run: |
          # pick the newest project wheel
          WHEEL=$(ls -t dist/*.whl | head -n1)
          # převeď na absolutní cestu, aby fungovala i z .pyapp
          case "$WHEEL" in
            /*) WHEEL_ABS="$WHEEL" ;;
            *)  WHEEL_ABS="$(pwd)/$WHEEL" ;;
          esac
          echo "wheel=${WHEEL_ABS}" >> "$GITHUB_OUTPUT"
          echo "Found wheel: ${WHEEL_ABS}"

      - name: Download PyApp source release
        run: |
          mkdir -p .pyapp && cd .pyapp
          curl -L https://github.com/ofek/pyapp/releases/latest/download/source.tar.gz -o source.tar.gz
          tar -xzf source.tar.gz --strip-components=1
          # sanity check
          [ -f Cargo.toml ] || (echo "PyApp source missing" && exit 1)

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            .pyapp/target
          key: cargo-${{ runner.os }}-pyapp-${{ hashFiles('.pyapp/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-pyapp-

      - name: Configure PyApp env (embed Python + project)
        env:
          WHEEL: ${{ steps.wheel.outputs.wheel }}
        run: |
          # Persist variables for subsequent steps via GitHub Actions env file
          echo "PYAPP_PROJECT_PATH=${WHEEL}" >> $GITHUB_ENV
          # Derive project name and version from pyproject.toml
          PROJ_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' pyproject.toml | head -n1)
          PROJ_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml | head -n1)
          # Fallback to names from wheel if parsing failed
          if [ -z "$PROJ_NAME" ]; then
            PROJ_NAME=$(basename "$WHEEL" | sed 's/-[0-9].*//')
          fi
          if [ -z "$PROJ_VERSION" ]; then
            PROJ_VERSION=$(basename "$WHEEL" | sed 's/^[^-]*-//' | cut -d'-' -f1)
          fi
          echo "PYAPP_PROJECT_NAME=${PROJ_NAME}" >> $GITHUB_ENV
          echo "PYAPP_PROJECT_VERSION=${PROJ_VERSION}" >> $GITHUB_ENV
          echo "PYAPP_EXEC_ENTRYPOINT=${EXEC_ENTRYPOINT}" >> $GITHUB_ENV
          echo "PYAPP_DISTRIBUTION_EMBED=1" >> $GITHUB_ENV
          echo "PYAPP_PYTHON_VERSION=${PY_VER}" >> $GITHUB_ENV
          echo "PYAPP_UV_ENABLED=1" >> $GITHUB_ENV
          # Optional knobs:
          # echo "PYAPP_SKIP_INSTALL=1" >> $GITHUB_ENV     # fully offline first run (with prebuilt env)
          # echo "PYAPP_DISTRIBUTION_VARIANT_CPU=v3" >> $GITHUB_ENV
          # echo "PYAPP_EXEC_MODULE=cli.zte" >> $GITHUB_ENV

      - name: Build PyApp (musl target)
        working-directory: .pyapp
        run: |
          # Build inside Alpine => musl (x86_64-unknown-linux-musl)
          cargo build --release
          mkdir -p ../dist/bin
          cp target/release/pyapp "../dist/bin/${APP_NAME}"
          chmod +x "../dist/bin/${APP_NAME}"
          ls -lah ../dist/bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-alpine-x86_64
          path: dist/bin/${{ env.APP_NAME }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-alpine-x86_64
          path: ./release

      - name: Compute tag and release names
        id: names
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "tag=alpine-exe-${SHORT_SHA}-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
          echo "name=Alpine single-exe ${SHORT_SHA} (#${GITHUB_RUN_NUMBER})" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.names.outputs.tag }}
          name: ${{ steps.names.outputs.name }}
          files: ./release/${{ env.APP_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
